/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teachme;
import Clases.Horario;
import teachme.TeachMe.*;
import static teachme.TeachMe.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import Clases.Asesor;
import Clases.Materia;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rogelio
 */
public class interfaz extends javax.swing.JFrame {

    Asesor asesorActual = new Asesor();
    /**
     * Creates new form interfaz
     * @param usuarioActual
     */
    public interfaz(Asesor usuarioActual) {
        initComponents();
        System.out.println(usuarioActual.getId());
        mostrarSesiones(usuarioActual.getId());
        lblMateria.setText(usuarioActual.getUsername());
        asesorActual = usuarioActual;
        pnlHoras.setVisible(false);
        pnlMaterias.setVisible(false);
        lblNombre.setText(asesorActual.getNombreCompleto());
    }

    private interfaz() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        btnAddHoras = new javax.swing.JButton();
        pnlHoras = new javax.swing.JPanel();
        cmbHoras = new javax.swing.JComboBox<>();
        btnAddhora = new javax.swing.JButton();
        errorHora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlMaterias = new javax.swing.JPanel();
        cmbmaterias = new javax.swing.JComboBox<>();
        btnAddmateria = new javax.swing.JButton();
        errormateria = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSesiones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, null));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asesor/imagenes/ii.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1300, 1300));
        jLabel1.setMinimumSize(new java.awt.Dimension(1300, 1300));
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 1300));

        lblMateria.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblMateria.setText("jLabel3");

        btnAddHoras.setText("Agrega Horas Disponibles");
        btnAddHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHorasActionPerformed(evt);
            }
        });

        cmbHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00" }));

        btnAddhora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asesor/imagenes/btnsave.png"))); // NOI18N
        btnAddhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddhoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHorasLayout = new javax.swing.GroupLayout(pnlHoras);
        pnlHoras.setLayout(pnlHorasLayout);
        pnlHorasLayout.setHorizontalGroup(
            pnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbHoras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHorasLayout.createSequentialGroup()
                        .addComponent(errorHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddhora, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlHorasLayout.setVerticalGroup(
            pnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHorasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddhora, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlHorasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(errorHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton1.setText("Agrega Mateias que impartes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbmaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas Digitales", "Programacion Estructurada", "Fisica I", "Fisica II", "Fisica III", "Fisica IV", "Quimica General", "Matematicas I", "Matematicas II", "Matematicas III", "Matematicas IV" }));

        btnAddmateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asesor/imagenes/btnsave.png"))); // NOI18N
        btnAddmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddmateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMateriasLayout = new javax.swing.GroupLayout(pnlMaterias);
        pnlMaterias.setLayout(pnlMateriasLayout);
        pnlMateriasLayout.setHorizontalGroup(
            pnlMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbmaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMateriasLayout.createSequentialGroup()
                        .addComponent(errormateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlMateriasLayout.setVerticalGroup(
            pnlMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbmaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errormateria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAddHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addGap(99, 99, 99))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(pnlHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblMateria)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblMateria)
                .addGap(29, 29, 29)
                .addComponent(btnAddHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asesor/imagenes/btnsalir.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblNombre.setText("User");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSesiones.setRowHeight(30);
        tablaSesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSesionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSesiones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        asesorActual = null;
        Index index = new Index();
        index.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHorasActionPerformed
        // TODO add your handling code here:
        pnlHoras.setVisible(true);
    }//GEN-LAST:event_btnAddHorasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pnlMaterias.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarSesiones(int idAsesor){
        tablaSesiones.setDefaultRenderer(Object.class, new Renderizar());
        JButton guardar = new JButton("Eliminar sesion");
        guardar.setName("e");
        DefaultTableModel modelo = new DefaultTableModel();
        try{
            Connection con;
            PreparedStatement ps;
            ResultSet res;
            con = getConection();
            String query = "SELECT sesion.id, usuario.nombre, usuario.ap_paterno, horarios.hora ";
            query += " FROM sesion INNER JOIN alumnos ON sesion.id_alumno = alumnos.id INNER JOIN usuario ON alumnos.id_usuario = usuario.id ";
            query += " INNER JOIN horarios ON horarios.id = sesion.id_horario WHERE sesion.id_asesor = "+ idAsesor;
            res = getTabla(query);
            modelo.setColumnIdentifiers(new Object[]{"No.","Nombre","Apellido","Hora","..."});
            if(res == null){
                //modelo.addRow(new Object[]{"No hay usuarios con este servicio","Sin usau"});
                System.out.println("No hay sesiones");
            }
            else{
                while(res.next()){
                    modelo.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),guardar});
                }
                tablaSesiones.setModel(modelo);                
                tablaSesiones.setPreferredScrollableViewportSize(tablaSesiones.getPreferredSize());
                System.out.println(asesorActual.getId());
            }
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }
    
    private void btnAddhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddhoraActionPerformed
        // TODO add your handling code here:
        String hora="", query;
        hora = cmbHoras.getSelectedItem().toString();
        try{
            Connection con = null;
            con = getConection();
            PreparedStatement ps;
            ResultSet res;
            Horario horaSeleccionada = BuscarHorario(hora);
            query = "INSERT INTO horariosasesor (id_asesor, id_horario, disponible) VALUES(?,?,?)";
            ps = (PreparedStatement) con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS); /* El nombre de la tabla*/
            ps.setInt(1, asesorActual.getId());
            ps.setInt(2, horaSeleccionada.getId());
            ps.setInt(3, 1);
            ps.executeUpdate();
            errorHora.setText("La hora se ha agregado correctamente");
        }catch(Exception e){
            errorHora.setText("Ha ocurrido un error al agregar la hora");
        }
    }//GEN-LAST:event_btnAddhoraActionPerformed

    private void btnAddmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddmateriaActionPerformed
        // TODO add your handling code here:
        String materiaStr, query;
        materiaStr = cmbmaterias.getSelectedItem().toString();
        try{
            Connection con = null;
            con = getConection();
            PreparedStatement ps;
            ResultSet res;
            Materia materia = BuscarMateria(materiaStr);
            query = "INSERT INTO materiasasesor (id_asesor, id_materia) VALUES(?,?)";
            ps = (PreparedStatement) con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS); /* El nombre de la tabla*/
            ps.setInt(1, asesorActual.getId());
            ps.setInt(2, materia.getId());
            ps.executeUpdate();
            errormateria.setText("La materia se ha agregado correctamente");
        }catch(Exception e){
            errormateria.setText("Ha ocurrido un error al agregar la materia");
        }
    }//GEN-LAST:event_btnAddmateriaActionPerformed

    private void eliminarSesion(int idSesion){
        try{
            Connection con = null;
            con = getConection();
            PreparedStatement ps;
            ResultSet res;
            String query = "DELETE FROM sesion WHERE id = ?";
            ps = (PreparedStatement) con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setInt(1, idSesion);
            ps.execute();
            //ps.executeUpdate();
            ps.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
            
    int clickTabla =0;
    private void tablaSesionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSesionesMouseClicked
        // TODO add your handling code here:
        clickTabla = this.tablaSesiones.rowAtPoint(evt.getPoint());
        int id = (int)tablaSesiones.getValueAt(clickTabla, 0);
        
        int column = tablaSesiones.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tablaSesiones.getRowHeight();
        
        if(row < tablaSesiones.getRowCount() && row >= 0 && column < tablaSesiones.getColumnCount() && column >= 0){
            Object value = tablaSesiones.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                if(boton.getName().equals("e")){
                    int confirm = JOptionPane.showConfirmDialog(null, "¿Eliminar esta sesión?", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    if(JOptionPane.OK_OPTION == confirm){
                        System.out.println("confirmadoo");
                        eliminarSesion(id);
                        //Thread.sleep(1000);
                        mostrarSesiones(asesorActual.getId());
                    }
                    //EVENTOS ELIMINAR
                }
            }
        }
    }//GEN-LAST:event_tablaSesionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddHoras;
    private javax.swing.JButton btnAddhora;
    private javax.swing.JButton btnAddmateria;
    private javax.swing.JComboBox<String> cmbHoras;
    private javax.swing.JComboBox<String> cmbmaterias;
    private javax.swing.JLabel errorHora;
    private javax.swing.JLabel errormateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlHoras;
    private javax.swing.JPanel pnlMaterias;
    private javax.swing.JTable tablaSesiones;
    // End of variables declaration//GEN-END:variables
}
